-- Auto-generated from database/immigration.duckdb by scripts/export_to_postgres.py
-- Safe to rerun: tables are created if missing; indexes are created if missing.

CREATE SCHEMA IF NOT EXISTS "immigration";
SET search_path TO "immigration";

CREATE TABLE IF NOT EXISTS "immigration"."visa_issuances" (
    "fiscal_year" BIGINT,
    "country" TEXT,
    "A-1" BIGINT,
    "A-2" BIGINT,
    "A-3" BIGINT,
    "B-1" BIGINT,
    "B-1,2" BIGINT,
    "B-2" BIGINT,
    "B-1,2/BCC" BIGINT,
    "B-1,2/BCV" BIGINT,
    "C-1" BIGINT,
    "C-1/D" BIGINT,
    "C-2" BIGINT,
    "C-3" BIGINT,
    "D" BIGINT,
    "D-CREW" BIGINT,
    "E-1" BIGINT,
    "E-2" BIGINT,
    "E-3" BIGINT,
    "E-3D" BIGINT,
    "E-3R" BIGINT,
    "F-1" BIGINT,
    "F-2" BIGINT,
    "F-3" BIGINT,
    "G-1" BIGINT,
    "G-2" BIGINT,
    "G-3" BIGINT,
    "G-4" BIGINT,
    "G-5" BIGINT,
    "H-1A" BIGINT,
    "H-1B" BIGINT,
    "H-1B1" BIGINT,
    "H-1C" BIGINT,
    "H-2A" BIGINT,
    "H-2B" BIGINT,
    "H-2R" BIGINT,
    "H-3" BIGINT,
    "H-4" BIGINT,
    "I" BIGINT,
    "J-1" BIGINT,
    "J-2" BIGINT,
    "K-1" BIGINT,
    "K-2" BIGINT,
    "K-3" BIGINT,
    "K-4" BIGINT,
    "L-1" BIGINT,
    "L-2" BIGINT,
    "M-1" BIGINT,
    "M-2" BIGINT,
    "M-3" BIGINT,
    "NATO-1" BIGINT,
    "NATO-2" BIGINT,
    "NATO-3" BIGINT,
    "NATO-4" BIGINT,
    "NATO-5" BIGINT,
    "NATO-6" BIGINT,
    "NATO-7" BIGINT,
    "N-8" BIGINT,
    "N-9" BIGINT,
    "O-1" BIGINT,
    "O-2" BIGINT,
    "O-3" BIGINT,
    "P-1" BIGINT,
    "P-2" BIGINT,
    "P-3" BIGINT,
    "P-4" BIGINT,
    "Q-1" BIGINT,
    "Q-2" BIGINT,
    "Q-3" BIGINT,
    "R-1" BIGINT,
    "R-2" BIGINT,
    "S-5" BIGINT,
    "S-6" BIGINT,
    "S-7" BIGINT,
    "TN" BIGINT,
    "TD" BIGINT,
    "T-1" BIGINT,
    "T-2" BIGINT,
    "T-3" BIGINT,
    "T-4" BIGINT,
    "T-5" BIGINT,
    "U-1" BIGINT,
    "U-2" BIGINT,
    "U-3" BIGINT,
    "U-4" BIGINT,
    "V-1" BIGINT,
    "V-2" BIGINT,
    "V-3" BIGINT,
    "Total Visas" BIGINT,
    "BCC" BIGINT,
    "Grand Total" BIGINT,
    "U-5" BIGINT,
    "E-2C" BIGINT,
    "CW-1" BIGINT,
    "CW-2" BIGINT,
    "T-6" BIGINT,
    "C-4" BIGINT,
    "C-4/D-3" BIGINT
);

CREATE TABLE IF NOT EXISTS "immigration"."niv_workload" (
    "visa_category" TEXT,
    "issued" BIGINT,
    "refused" BIGINT,
    "total_applications" BIGINT,
    "refusal_rate" DOUBLE PRECISION,
    "fiscal_year" BIGINT
);

CREATE TABLE IF NOT EXISTS "immigration"."b_visa_refusals" (
    "nationality" TEXT,
    "adjusted_refusal_rate" DOUBLE PRECISION,
    "fiscal_year" BIGINT
);

CREATE TABLE IF NOT EXISTS "immigration"."country_mapping" (
    "original_name" TEXT,
    "standard_name" TEXT
);

CREATE TABLE IF NOT EXISTS "immigration"."b_visa_workload_by_country" (
    "country" TEXT,
    "fiscal_year" INTEGER,
    "b_visa_issued" BIGINT,
    "refusal_rate_pct" DOUBLE PRECISION,
    "est_refused" INTEGER,
    "est_applications" INTEGER,
    "total_niv_issued" BIGINT
);

CREATE TABLE IF NOT EXISTS "immigration"."niv_workload_by_country" (
    "country" TEXT,
    "fiscal_year" INTEGER,
    "total_issued" BIGINT,
    "est_refused" INTEGER,
    "est_applications" INTEGER,
    "b_visa_issued" BIGINT,
    "b_visa_refusal_rate" DOUBLE PRECISION,
    "h1b_issued" BIGINT,
    "f1_issued" BIGINT,
    "l1_issued" BIGINT,
    "j1_issued" BIGINT
);

CREATE TABLE IF NOT EXISTS "immigration"."visa_ineligibility_grounds" (
    "ina_section" TEXT,
    "description" TEXT,
    "iv_finding" BIGINT,
    "iv_overcome" BIGINT,
    "niv_finding" BIGINT,
    "niv_overcome" BIGINT,
    "fiscal_year" BIGINT
);

CREATE TABLE IF NOT EXISTS "immigration"."visas_by_consular_post" (
    "region" TEXT,
    "issuing_office" TEXT,
    "iv_issued" BIGINT,
    "niv_issued" BIGINT,
    "border_crossing_cards" BIGINT,
    "is_total" BOOLEAN,
    "fiscal_year" BIGINT
);

CREATE TABLE IF NOT EXISTS "immigration"."h1b_lca_cases" (
    "case_number" TEXT,
    "case_status" TEXT,
    "received_date" DATE,
    "decision_date" DATE,
    "visa_class" TEXT,
    "job_title" TEXT,
    "soc_code" TEXT,
    "soc_title" TEXT,
    "full_time_position" TEXT,
    "begin_date" DATE,
    "end_date" DATE,
    "total_worker_positions" BIGINT,
    "new_employment" BIGINT,
    "continued_employment" BIGINT,
    "change_previous_employment" BIGINT,
    "new_concurrent_employment" BIGINT,
    "change_employer" BIGINT,
    "amended_petition" BIGINT,
    "employer_name" TEXT,
    "trade_name_dba" TEXT,
    "employer_city" TEXT,
    "employer_state" TEXT,
    "employer_postal_code" TEXT,
    "employer_country" TEXT,
    "naics_code" BIGINT,
    "worksite_workers" BIGINT,
    "secondary_entity" BOOLEAN,
    "secondary_entity_business_name" TEXT,
    "worksite_city" TEXT,
    "worksite_county" TEXT,
    "worksite_state" TEXT,
    "worksite_postal_code" TEXT,
    "wage_rate_of_pay_from" DOUBLE PRECISION,
    "wage_rate_of_pay_to" DOUBLE PRECISION,
    "wage_unit_of_pay" TEXT,
    "prevailing_wage" DOUBLE PRECISION,
    "pw_unit_of_pay" TEXT,
    "pw_wage_level_raw" TEXT,
    "wage_level" TEXT,
    "weighted_entries_per_worker" BIGINT,
    "annual_wage_from" DOUBLE PRECISION,
    "annual_wage_to" DOUBLE PRECISION,
    "annual_prevailing_wage" DOUBLE PRECISION,
    "wage_plausibility_flag" TEXT,
    "total_worksite_locations" BIGINT,
    "h1b_dependent" BOOLEAN,
    "willful_violator" BOOLEAN,
    "support_h1b" TEXT,
    "statutory_basis" TEXT,
    "fiscal_year" BIGINT,
    "quarter" TEXT,
    "source_file" TEXT
);

CREATE TABLE IF NOT EXISTS "immigration"."h1b_lca_worksites" (
    "case_number" TEXT,
    "worksite_workers" BIGINT,
    "secondary_entity" TEXT,
    "secondary_entity_business_name" TEXT,
    "worksite_city" TEXT,
    "worksite_county" TEXT,
    "worksite_state" TEXT,
    "worksite_postal_code" TEXT,
    "wage_rate_of_pay_from" DOUBLE PRECISION,
    "wage_rate_of_pay_to" DOUBLE PRECISION,
    "wage_unit_of_pay" TEXT,
    "prevailing_wage" DOUBLE PRECISION,
    "pw_unit_of_pay" TEXT,
    "pw_wage_level_raw" TEXT,
    "wage_level" TEXT,
    "weighted_entries_per_worker" BIGINT,
    "annual_wage_from" DOUBLE PRECISION,
    "annual_wage_to" DOUBLE PRECISION,
    "annual_prevailing_wage" DOUBLE PRECISION,
    "wage_plausibility_flag" TEXT,
    "fiscal_year" BIGINT,
    "quarter" TEXT,
    "source_file" TEXT
);

CREATE TABLE IF NOT EXISTS "immigration"."h1b_wage_summary" (
    "fiscal_year" BIGINT,
    "quarter" TEXT,
    "employer_name" TEXT,
    "soc_code" TEXT,
    "soc_title" TEXT,
    "worksite_state" TEXT,
    "worksite_city" TEXT,
    "wage_level" TEXT,
    "case_count" BIGINT,
    "worker_positions" NUMERIC,
    "median_annual_wage" DOUBLE PRECISION,
    "avg_annual_wage" DOUBLE PRECISION,
    "min_annual_wage" DOUBLE PRECISION,
    "max_annual_wage" DOUBLE PRECISION,
    "weighted_entries" NUMERIC
);

CREATE TABLE IF NOT EXISTS "immigration"."h1b_cap_season_proxy" (
    "case_number" TEXT,
    "case_status" TEXT,
    "received_date" DATE,
    "decision_date" DATE,
    "visa_class" TEXT,
    "job_title" TEXT,
    "soc_code" TEXT,
    "soc_title" TEXT,
    "full_time_position" TEXT,
    "begin_date" DATE,
    "end_date" DATE,
    "total_worker_positions" BIGINT,
    "new_employment" BIGINT,
    "continued_employment" BIGINT,
    "change_previous_employment" BIGINT,
    "new_concurrent_employment" BIGINT,
    "change_employer" BIGINT,
    "amended_petition" BIGINT,
    "employer_name" TEXT,
    "trade_name_dba" TEXT,
    "employer_city" TEXT,
    "employer_state" TEXT,
    "employer_postal_code" TEXT,
    "employer_country" TEXT,
    "naics_code" BIGINT,
    "worksite_workers" BIGINT,
    "secondary_entity" BOOLEAN,
    "secondary_entity_business_name" TEXT,
    "worksite_city" TEXT,
    "worksite_county" TEXT,
    "worksite_state" TEXT,
    "worksite_postal_code" TEXT,
    "wage_rate_of_pay_from" DOUBLE PRECISION,
    "wage_rate_of_pay_to" DOUBLE PRECISION,
    "wage_unit_of_pay" TEXT,
    "prevailing_wage" DOUBLE PRECISION,
    "pw_unit_of_pay" TEXT,
    "pw_wage_level_raw" TEXT,
    "wage_level" TEXT,
    "weighted_entries_per_worker" BIGINT,
    "annual_wage_from" DOUBLE PRECISION,
    "annual_wage_to" DOUBLE PRECISION,
    "annual_prevailing_wage" DOUBLE PRECISION,
    "wage_plausibility_flag" TEXT,
    "total_worksite_locations" BIGINT,
    "h1b_dependent" BOOLEAN,
    "willful_violator" BOOLEAN,
    "support_h1b" TEXT,
    "statutory_basis" TEXT,
    "fiscal_year" BIGINT,
    "quarter" TEXT,
    "source_file" TEXT,
    "proxy_worker_positions" BIGINT,
    "proxy_weighted_entries" BIGINT
);

CREATE TABLE IF NOT EXISTS "immigration"."h1b_public_wage_fact" (
    "wage_fact_id" TEXT,
    "fiscal_year" BIGINT,
    "quarter" TEXT,
    "case_source_file" TEXT,
    "worksite_source_file" TEXT,
    "case_number" TEXT,
    "worksite_sequence" BIGINT,
    "case_status" TEXT,
    "received_date" DATE,
    "decision_date" DATE,
    "visa_class" TEXT,
    "begin_date" DATE,
    "end_date" DATE,
    "employer_name" TEXT,
    "trade_name_dba" TEXT,
    "employer_city" TEXT,
    "employer_state" TEXT,
    "employer_postal_code" TEXT,
    "employer_country" TEXT,
    "naics_code" BIGINT,
    "job_title" TEXT,
    "soc_code" TEXT,
    "soc_title" TEXT,
    "full_time_position" TEXT,
    "case_worker_positions" BIGINT,
    "new_employment" BIGINT,
    "continued_employment" BIGINT,
    "change_previous_employment" BIGINT,
    "new_concurrent_employment" BIGINT,
    "change_employer" BIGINT,
    "amended_petition" BIGINT,
    "worker_positions" BIGINT,
    "worksite_city" TEXT,
    "worksite_county" TEXT,
    "worksite_state_raw" TEXT,
    "worksite_postal_code" TEXT,
    "secondary_entity" TEXT,
    "secondary_entity_business_name" TEXT,
    "wage_rate_of_pay_from" DOUBLE PRECISION,
    "wage_rate_of_pay_to" DOUBLE PRECISION,
    "wage_unit_of_pay" TEXT,
    "prevailing_wage" DOUBLE PRECISION,
    "pw_unit_of_pay" TEXT,
    "pw_wage_level_raw" TEXT,
    "wage_level" TEXT,
    "wage_weight" BIGINT,
    "annual_wage_from" DOUBLE PRECISION,
    "annual_wage_to" DOUBLE PRECISION,
    "annual_prevailing_wage" DOUBLE PRECISION,
    "wage_plausibility_flag" TEXT,
    "total_worksite_locations" BIGINT,
    "h1b_dependent" BOOLEAN,
    "willful_violator" BOOLEAN,
    "support_h1b" TEXT,
    "statutory_basis" TEXT,
    "worksite_state" TEXT,
    "weighted_entries" BIGINT,
    "wage_premium_pct" DOUBLE PRECISION,
    "salary_band" TEXT,
    "cap_season_proxy_flag" BOOLEAN
);

CREATE INDEX IF NOT EXISTS "idx_h1b_lca_cases_case_number" ON "immigration"."h1b_lca_cases" ("case_number");
CREATE INDEX IF NOT EXISTS "idx_h1b_lca_cases_employer_name" ON "immigration"."h1b_lca_cases" ("employer_name");
CREATE INDEX IF NOT EXISTS "idx_h1b_lca_cases_soc_code" ON "immigration"."h1b_lca_cases" ("soc_code");
CREATE INDEX IF NOT EXISTS "idx_h1b_lca_cases_worksite_state" ON "immigration"."h1b_lca_cases" ("worksite_state");
CREATE INDEX IF NOT EXISTS "idx_h1b_lca_worksites_case_number" ON "immigration"."h1b_lca_worksites" ("case_number");
CREATE INDEX IF NOT EXISTS "idx_h1b_public_wage_fact_case_number" ON "immigration"."h1b_public_wage_fact" ("case_number");
CREATE INDEX IF NOT EXISTS "idx_h1b_public_wage_fact_employer_name" ON "immigration"."h1b_public_wage_fact" ("employer_name");
CREATE INDEX IF NOT EXISTS "idx_h1b_public_wage_fact_soc_code" ON "immigration"."h1b_public_wage_fact" ("soc_code");
CREATE INDEX IF NOT EXISTS "idx_h1b_public_wage_fact_worksite_state" ON "immigration"."h1b_public_wage_fact" ("worksite_state");
CREATE INDEX IF NOT EXISTS "idx_h1b_public_wage_fact_wage_level" ON "immigration"."h1b_public_wage_fact" ("wage_level");
CREATE INDEX IF NOT EXISTS "idx_h1b_public_wage_fact_cap_season_proxy_flag" ON "immigration"."h1b_public_wage_fact" ("cap_season_proxy_flag");
CREATE INDEX IF NOT EXISTS "idx_h1b_cap_season_proxy_case_number" ON "immigration"."h1b_cap_season_proxy" ("case_number");
CREATE INDEX IF NOT EXISTS "idx_h1b_wage_summary_employer_name" ON "immigration"."h1b_wage_summary" ("employer_name");
CREATE INDEX IF NOT EXISTS "idx_h1b_wage_summary_soc_code" ON "immigration"."h1b_wage_summary" ("soc_code");
CREATE INDEX IF NOT EXISTS "idx_visa_issuances_country" ON "immigration"."visa_issuances" ("country");
CREATE INDEX IF NOT EXISTS "idx_visa_issuances_fiscal_year" ON "immigration"."visa_issuances" ("fiscal_year");

-- Future v1.2 selection-odds tables. These are intentionally empty until
-- scripts/model_h1b_selection_odds.py is implemented.
CREATE TABLE IF NOT EXISTS "immigration"."h1b_selection_parameters" (
    selection_fy INTEGER,
    selection_round TEXT,
    eligible_registrations BIGINT,
    selected_registrations BIGINT,
    selected_beneficiaries BIGINT,
    regular_cap_slots BIGINT,
    masters_cap_slots BIGINT,
    registration_start_date DATE,
    registration_end_date DATE,
    selection_notice_date DATE,
    filing_start_date DATE,
    filing_end_date DATE,
    source_url TEXT,
    source_note TEXT,
    as_of_date DATE
);

CREATE TABLE IF NOT EXISTS "immigration"."h1b_profile_probability_index" (
    selection_fy INTEGER,
    employer_name TEXT,
    soc_code TEXT,
    soc_title TEXT,
    worksite_state TEXT,
    worksite_city TEXT,
    wage_level TEXT,
    wage_weight INTEGER,
    profile_bucket TEXT,
    comparable_case_count BIGINT,
    comparable_proxy_positions DOUBLE PRECISION,
    comparable_weighted_entries DOUBLE PRECISION,
    estimated_probability DOUBLE PRECISION,
    p05_probability DOUBLE PRECISION,
    p95_probability DOUBLE PRECISION,
    confidence_score TEXT,
    benchmark_probability DOUBLE PRECISION,
    percentile_vs_comparable_wages DOUBLE PRECISION
);
